// server/pdf/buildPurchaseOrderHtml.js
/**
 * Build HTML for Purchase Order PDF
 * Takes PO data and generates HTML from template
 */
const fs = require('fs');
const path = require('path');

module.exports = function buildPurchaseOrderHtml(poData) {
  // Read template
  const templatePath = path.join(__dirname, 'purchase-order-template.html');
  let html = fs.readFileSync(templatePath, 'utf8');

  // Format dates
  const formatDate = (dateStr) => {
    if (!dateStr) return '—';
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-IN', { 
      year: 'numeric', 
      month: '2-digit', 
      day: '2-digit' 
    });
  };

  // Calculate totals
  let subTotal = 0;
  const itemsRows = poData.items
    .map((item, idx) => {
      const amount = (item.ordered_qty || 0) * (item.unit_price || 0);
      subTotal += amount;
      
      return `
        <tr>
          <td style="text-align:center;">${idx + 1}</td>
          <td>
            <div style="font-weight:600;">${item.product_name || ''}</div>
            <div style="font-size:10px; color:#666;">${item.product_description || ''}</div>
          </td>
          <td class=\"qty text-right\">${(item.ordered_qty || 0).toFixed(2)}</td>
          <td class="rate text-right">₹ ${(item.unit_price || 0).toFixed(2)}</td>
          <td class="amount text-right">₹ ${amount.toFixed(2)}</td>
        </tr>
      `;
    })
    .join('');

  const tax = 0; // Can be calculated based on tax rules
  const grandTotal = subTotal + tax;

  // Replace placeholders
  html = html.replace('{{po_number}}', poData.po_number || '—');
  html = html.replace('{{order_date}}', formatDate(poData.order_date));
  html = html.replace('{{vendor_name}}', poData.vendor_name || '—');
  html = html.replace('{{vendor_gst}}', poData.vendor_gst || '—');
  html = html.replace('{{contact_person}}', poData.contact_person || '—');
  html = html.replace('{{contact_email}}', poData.contact_email || '—');
  html = html.replace('{{contact_phone}}', poData.contact_phone || '—');
  html = html.replace('{{bill_to_name}}', poData.bill_to_name || 'Prayosha Automation Pvt Ltd');
  html = html.replace('{{bill_to_address}}', poData.bill_to_address || 'Vadodara, Gujarat 390011, India');
  html = html.replace('{{indent_number}}', poData.indent_number || '—');
  html = html.replace('{{vendor_quote_no}}', poData.vendor_quote_no || '—');
  html = html.replace('{{vendor_quote_date}}', formatDate(poData.vendor_quote_date));
  html = html.replace('{{delivery_date}}', formatDate(poData.delivery_date));
  html = html.replace('{{payment_terms}}', poData.payment_terms || '—');
  html = html.replace('{{items_rows}}', itemsRows);
  html = html.replace('{{sub_total}}', subTotal.toFixed(2));
  html = html.replace('{{tax}}', tax.toFixed(2));
  html = html.replace('{{grand_total}}', grandTotal.toFixed(2));
  html = html.replace('{{remarks}}', poData.remarks || 'Thank you for your business!');
  html = html.replace('{{logo_main}}', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=='); // placeholder
  html = html.replace('{{footer_note}}', 'Generated by Prayosha QMS');

  return html;
};
